{{- if eq .Values.global.deploymentMode "oss"  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airbyte-gcs-log-creds
type: Opaque
data:
  gcp.json: "{{ .Values.global.logs.gcs.credentialsJson }}"
{{- end }}